[build]
  command = "npm run build:client"
  publish = "dist/spa"
  environment = { NODE_VERSION = "20" }

[functions]
  directory = "netlify/functions"
  external_node_modules = ["express", "serverless-http", "cors", "@prisma/client"]
  node_bundler = "esbuild"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"